server:
  port: 10086
spring:
  application:
    name: ly-retistry
eureka:
  client:
    fetch-registry: false #是否检索eureka其他服务
    register-with-eureka: false #是否注册自身
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
  server:
    enable-self-preservation: false #关闭自我保护
    eviction-interval-timer-in-ms: 5000 #每隔5秒进行一次服务列表清理




